#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ActivityTransition.Resource", IsApplication=true)]

namespace ActivityTransition
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int Fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fade_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Pushdown_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Pushdown_out = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Pushup_in = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Pushup_out = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Side_in_left = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int Side_in_right = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int Side_out_left = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int Side_out_right = 2130968585;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int logo = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int btnRun = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int choosedInTransition = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int choosedOutTransition = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int spinInTransactions = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int spinOutTransactions = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Result = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int Fade_in = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int fade_out = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int Pushdown_in = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int Pushdown_out = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int Pushup_in = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int Pushup_out = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int Side_in_left = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int Side_in_right = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int Side_out_left = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int Side_out_right = 2131034121;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060009
			public const int AddedToClipboard = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int NoTransitionSpinnerText = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int buttonRun = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int hintCopyToClipboard = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int promptInSpinner = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int promptOutSpinner = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int promptSpinner = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int resultInSpinner = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int resultOutSpinner = 2131099654;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MyTransitionTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
